### ISSUE TITLE
WoW friends not showing

### ISSUE THREAD

**Issue by Painstormx** [grdn1337/wow-addon-ifriends#1]
Newest version for Classic.
Battle.Net friends show up, but WoW friends don't.
They do seem to be counted though in the xx/yy counter.
Tried toggling "Display WoW friends....", but that didn't do anything.

Using Bazooka for showing data.

**Comment by letmeusemyname** [comment]
I'm having the same issue, using Chocolatebar as the broker. 

Getting this lua error: 
nterface\AddOns\iFriends\Columns.lua:246: attempt to concatenate field 'CLASS' (a nil value)
Time: Fri May 22 14:48:36 2020
Count: 1
Stack: Interface\AddOns\iFriends\Columns.lua:246: attempt to concatenate field 'CLASS' (a nil value)
