### ISSUE TITLE
8.2.5 Retail: fix for deprecated functions BNGetFriendInfo and BNGetFriendGameAccountInfo

### ISSUE THREAD

**Issue by speedwaystar** [grdn1337/wow-addon-ifriends#4]
as above, BNGetFriendInfo and BNGetFriendGameAccount were removed from the API in 8.2.5

https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/AddOns/Blizzard_Deprecated/Deprecated_8_2_5.lua

a fix which *should* work is below (however, see caveat)

`
function iFriends:SetupFriendsData(friendsOn, bnetOn)
		_G.wipe(self.Roster);
		_G.wipe(self.BNRoster);
		
		-- preventing Lua from declaring local values 10000x times per loop
		local _, charName, charLevel, charClass, charZone, isOnline, charStatus, charNote;
		local pID, presenceName, battleTag, isBattleTagPresence, toonID, isAFK, isDND, broadcastText, numToons, broadcastTime; -- additional BNET vars
		local hasFocus, client, realmName, realmID, charFaction, charRace, charGuild, toonID; -- toon specific vars
		
		local now = time();
		
		-- iterate through our friends
		for i = 1, friendsOn do
			charName, charLevel, charClass, charZone, isOnline, charStatus, charNote = _G.GetFriendInfo(i);
			
			if( isOnline ) then
				self.Roster[i] = {
					[1] = charName,
					[2] = charLevel,
					[3] = charClass,
					[4] = charZone or _G.UNKNOWN,  -- actually may happen o_O
					[5] = charStatus or "",
					[6] = charNote or ""
				};
				
				setmetatable(self.Roster[i], mt);
			end
		end
		
		-- iterate through our battle.net friends, if battle.net is connected
		if( _G.BNFeaturesEnabledAndConnected() ) then
			local rosterIndex = 1;

			for i = 1, bnetOn do
				-- determines whether a friend logged into WoW or another game
				local loggedWoW = false;
				local loggedApp = false;
				local loggedGame = false;
			
				local accountInfo = C_BattleNet.GetFriendAccountInfo(i)

				--if( isOnline ) then					
					local charStatus = "";
					if( accountInfo.isAFK ) then
						charStatus = ("<%s>"):format(_G.AFK);
					elseif( accountInfo.isDND ) then
						charStatus = ("<%s>"):format(_G.DND);
					end
					
					-- add broadcast time to broadcast text, CurseForge Ticket #4 by CenujiDev
					local broadcastText = accountInfo.customMessage
					if ( broadcastText and broadcastText ~= "" ) then
						broadcastText = ("%s (%s)"):format(broadcastText, _G.SecondsToTime(now - accountInfo.customMessageTime, false, true, 1));
					end
					
					-- create roster table without any info
					local set = {
						[1]  = "",
						[2]  = "",
						[3]  = "",
						[4]  = "",
						[5]  = charStatus,
						[6]  = accountInfo.note or "",
						[7]  = accountInfo.bnetAccountID,
						[8]  = accountInfo.gameAccountInfo.gameAccountID,
						[9]  = accountInfo.accountName,
						[10] = accountInfo.battleTag or "",
						[11] = broadcastText or "",
						[12] = "",
						[13] = "",
						[14] = "",
						[15] = ""
					};
					
					-- scan thru friends logged in Blizzard games/apps
					numToons = C_BattleNet.GetFriendNumGameAccounts(i);
					
					for t = 1, numToons do
						
						local gameAccountInfo = C_BattleNet.GetFriendGameAccountInfo(i, t)
						-- save if the player is logged into WoW, all other data will be overwritten
						if( gameAccountInfo.clientProgram == _G.BNET_CLIENT_WOW ) then
							loggedWoW = true;
							
							set[1]  = gameAccountInfo.characterName;
							set[2]  = tonumber(gameAccountInfo.characterLevel); -- the bnet API returns the level as string. WTH
							set[3]  = gameAccountInfo.className;
							set[4]  = ((not gameAccountInfo.areaName or gameAccountInfo.areaName == "") and _G.UNKNOWN or gameAccountInfo.areaName); -- currently no zones in beta O_o
							set[12] = gameAccountInfo.clientProgram;
							set[13] = gameAccountInfo.realmName;
							set[14] = gameAccountInfo.factionName;
							set[15] = gameAccountInfo.raceName;
						else
							-- only if not logged into WoW!
							-- if the player is logged on the b.net app, only the client will be overwritten
							if( gameAccountInfo.clientProgram == _G.BNET_CLIENT_APP or gameAccountInfo.clientProgram == "BSAp" ) then
								loggedApp = true;
								
								if( not loggedGame and not loggedWoW ) then
									set[12] = gameAccountInfo.clientProgram;
								end
							-- if not logged into WoW, but another game, some data will be overwritten
							else
								loggedGame = true;
								
								if( not loggedWoW ) then
									set[1]  = gameAccountInfo.characterName;
									set[4]  = gameAccountInfo.richPresence;
									set[12] = gameAccountInfo.clientProgram;
								end
							end
						end
					end

					if( set[12] ~= "" ) then
						self.BNRoster[rosterIndex] = set;
						setmetatable(self.BNRoster[rosterIndex], mt);

						rosterIndex = rosterIndex + 1;
					end
				--end
			end -- end for
		end -- end if battle.net
		
	end -- end function
end
`

Caveat: CanCooperateWithGameAccount now throws this error:

1x FrameXML\FriendsFrame.lua:2287: attempt to index local 'accountInfo' (a number value)
FrameXML\FriendsFrame.lua:2287: in function `CanCooperateWithGameAccount'
iFriends\Columns.lua:190: in function `scriptUse'
iFriends\iFriends-8.2.1.lua:425: in function `?'
iLib\iLib-600100.lua:459: in function <iLib\iLib.lua:452>
iLib\iLib-600100.lua:491: in function `GetTooltip'
iSocial\iSocial-8.2.0.lua:60: in function `OnEnter'
Bazooka\Bazooka-v2.9.3.lua:1583: in function `showTip'
Bazooka\Bazooka-v2.9.3.lua:1388: in function <Bazooka\Bazooka.lua:1379>

this may be unrelated -- see issue https://github.com/grdn1337/wow-addon-ifriends/issues/2#issue-499871970

**Comment by tb1337** [comment]
Closed this due to new release...
